#!/usr/bin/env python3
"""Generate pass-through COM wrapper bodies + vtables from the real d3d9.h.

Slot order and every method signature are taken from the SDK-style header that
the compiler will itself use, so a slot can never be mis-numbered by hand.
Methods named in CUSTOM are not generated: the .c file defines them and the
generated vtable initializer refers to them by the same WD_/W9_/WSB_ name.

Usage:  gen_wrappers.py <path-to-d3d9.h> <output-dir>
"""

import os
import re
import sys

# Interfaces to wrap: (interface name, symbol prefix, {methods implemented by hand})
INTERFACES = [
    ("IDirect3D9", "W9_", {
        "QueryInterface", "AddRef", "Release", "CreateDevice",
    }),
    ("IDirect3DDevice9", "WD_", {
        "QueryInterface", "AddRef", "Release",
        "Present", "BeginScene", "EndScene", "Clear", "Reset",
        "DrawPrimitive", "DrawIndexedPrimitive",
        "DrawPrimitiveUP", "DrawIndexedPrimitiveUP",
        "SetRenderState", "SetTextureStageState", "SetTexture",
        "SetFVF", "SetVertexDeclaration", "SetStreamSource", "SetIndices",
        "SetViewport", "SetVertexShader", "SetPixelShader",
        "BeginStateBlock", "EndStateBlock", "CreateStateBlock",
        "CreateVertexBuffer", "CreateIndexBuffer", "ProcessVertices",
    }),
    ("IDirect3DStateBlock9", "WSB_", {
        "QueryInterface", "AddRef", "Release", "Apply",
    }),
    ("IDirect3DVertexBuffer9", "WVB_", {
        "QueryInterface", "AddRef", "Release", "Lock", "Unlock",
    }),
    ("IDirect3DIndexBuffer9", "WIB_", {
        "QueryInterface", "AddRef", "Release", "Lock", "Unlock",
    }),
]

COMMENT = re.compile(r"/\*.*?\*/", re.S)
DECL_RE = re.compile(
    r"STDMETHOD_\(\s*(?P<ret>[^,]+?)\s*,\s*(?P<name>\w+)\s*\)\s*\((?P<args>.*)\)\s*$"
    r"|"
    r"STDMETHOD\(\s*(?P<name2>\w+)\s*\)\s*\((?P<args2>.*)\)\s*$",
    re.S,
)
TOKENS = re.compile(r"[A-Za-z_]\w*|\*")
QUALIFIERS = {"const", "CONST", "struct", "unsigned", "signed", "volatile", "far", "FAR"}


def param_name(decl):
    """Return the parameter's name, or None if the declarator is unnamed.

    Unnamed if the last token is a '*' (e.g. `D3DLIGHT9*`), or if removing the
    trailing identifier would leave no type behind (e.g. `unsigned int`).
    """
    toks = TOKENS.findall(decl)
    if not toks or toks[-1] == "*":
        return None
    if not any(t not in QUALIFIERS and t != "*" for t in toks[:-1]):
        return None
    return toks[-1]


def split_args(text):
    out, depth, cur = [], 0, ""
    for ch in text:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur)
    return [a.strip() for a in out if a.strip()]


def parse_interface(header_text, iface):
    start = header_text.index("DECLARE_INTERFACE_IID_(%s," % iface)
    body = header_text[start:header_text.index("\n};", start)]
    body = COMMENT.sub(" ", body)
    methods = []
    for chunk in body.split("PURE;"):
        chunk = chunk.strip()
        if "STDMETHOD" not in chunk:
            continue
        chunk = chunk[chunk.index("STDMETHOD"):]
        m = DECL_RE.search(" ".join(chunk.split()))
        if not m:
            raise SystemExit("unparsed method declaration in %s: %r" % (iface, chunk))
        name = m.group("name") or m.group("name2")
        ret = (m.group("ret") or "HRESULT").strip()
        args = (m.group("args") if m.group("name") else m.group("args2")).strip()
        if args == "THIS":
            params = []
        elif args.startswith("THIS_"):
            params = split_args(args[len("THIS_"):])
        else:
            raise SystemExit("%s::%s does not take THIS: %r" % (iface, name, args))
        named = []
        for i, p in enumerate(params):
            nm = param_name(p)
            if nm is None:
                # Unnamed in the header (e.g. GetLight's `D3DLIGHT9*`); give it
                # a name so the forwarder can pass it on.
                nm = "beaArg%d" % (i + 1)
                p = "%s %s" % (p, nm)
            named.append((p, nm))
        methods.append((ret, name, named))
    return methods


def emit(iface, prefix, custom, methods):
    lines = [
        "/* GENERATED by tools/d3d9-proxy/gen_wrappers.py -- do not edit. */",
        "/* Source of truth for slot order and signatures: d3d9.h as compiled. */",
        "",
    ]
    for ret, name, params in methods:
        if name in custom:
            lines.append("/* %s: hand-written in wrap.c */" % name)
            continue
        sig = ", ".join(["%s *This" % iface] + [p for p, _ in params])
        call = ", ".join(["real"] + [n for _, n in params])
        lines.append("static %s STDMETHODCALLTYPE %s%s(%s) {" % (ret, prefix, name, sig))
        lines.append("    %s *real = BEA_REAL(This);" % iface)
        if ret.strip() == "void":
            lines.append("    real->lpVtbl->%s(%s);" % (name, call))
        else:
            lines.append("    return real->lpVtbl->%s(%s);" % (name, call))
        lines.append("}")
    lines.append("")
    lines.append("static %sVtbl bea_%s_vtbl = {" % (iface, prefix.rstrip("_").lower()))
    for _, name, _ in methods:
        lines.append("    .%s = %s%s," % (name, prefix, name))
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main():
    header, outdir = sys.argv[1], sys.argv[2]
    text = open(header, "r", encoding="utf-8", errors="replace").read()
    os.makedirs(outdir, exist_ok=True)
    for iface, prefix, custom in INTERFACES:
        methods = parse_interface(text, iface)
        names = {m[1] for m in methods}
        missing = custom - names
        if missing:
            raise SystemExit("%s: CUSTOM names not present in header: %s"
                             % (iface, sorted(missing)))
        path = os.path.join(outdir, "%s.inc" % iface.lower())
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(emit(iface, prefix, custom, methods))
        sys.stderr.write("%s: %d slots (%d generated, %d hand-written) -> %s\n"
                         % (iface, len(methods), len(methods) - len(custom),
                            len(custom), path))


if __name__ == "__main__":
    main()
