class_name CareerSave
extends RefCounted
## MIT companion byte codec. It performs no filesystem operations.
## Format reference: MIT AppCore/BesFilePatcher.cs, not the GPL rebuild.
## Container recognition is not proof that arbitrary bytes were generated by the game.

const SIZE: int = 10004
const VERSION_WORD: int = 0x4BD1
const MAX_KILLS: int = 0x00FFFFFF
const CATEGORY_NAMES: PackedStringArray = [
	"Aircraft", "Vehicles", "Emplacements", "Infantry", "Mechs"
]
const KILLS_OFFSET: int = 0x23F6
const NODE_OFFSET: int = 0x0006
const LINK_OFFSET: int = 0x1906
const GOODIE_OFFSET: int = 0x1F46
const TECH_OFFSET: int = 0x240A
const RANK_NAMES: Dictionary = {
	0x3F800000: "S", 0x3F4CCCCD: "A", 0x3F19999A: "B",
	0x3EB33333: "C", 0x3E19999A: "D", 0x00000000: "E",
	0xBF800000: "None"
}


static func inspect(bytes: PackedByteArray) -> Dictionary:
	var validation: Dictionary = _validate(bytes)
	if not validation.ok:
		return validation
	var kills: Array[int] = []
	var packed: Array[int] = []
	for category: int in range(CATEGORY_NAMES.size()):
		var raw: int = bytes.decode_u32(KILLS_OFFSET + category * 4)
		kills.append(raw & MAX_KILLS)
		packed.append(raw >> 24)

	var nodes: Array[Dictionary] = []
	var node_census: Dictionary = {"used": 0, "completed": 0, "incomplete": 0, "unused": 0}
	for index: int in range(100):
		var offset: int = NODE_OFFSET + index * 64
		var world: int = bytes.decode_u32(offset + 0x10)
		var complete_raw: int = bytes.decode_u32(offset + 0x04)
		var rank_bits: int = bytes.decode_u32(offset + 0x3C)
		var used: bool = world != 0
		var completed: bool = used and complete_raw != 0
		nodes.append({
			"index": index, "offset": offset, "world": world, "used": used,
			"complete_raw": complete_raw, "completed": completed,
			"attempts": bytes.decode_u32(offset + 0x38),
			"rank_bits": rank_bits, "rank_value": bytes.decode_float(offset + 0x3C),
			"rank": RANK_NAMES.get(rank_bits, "Unmapped"),
			"rank_known": RANK_NAMES.has(rank_bits)
		})
		if used:
			node_census.used += 1
			node_census["completed" if completed else "incomplete"] += 1
		else:
			node_census.unused += 1

	var links: Array[Dictionary] = []
	var link_census: Dictionary = {"used": 0, "locked": 0, "complete": 0, "broken": 0, "unknown": 0, "unused": 0}
	for index: int in range(200):
		var offset: int = LINK_OFFSET + index * 8
		var state: int = bytes.decode_u32(offset)
		var to_node: int = bytes.decode_u32(offset + 4)
		var used: bool = to_node != 0xFFFFFFFF
		var label: String = _link_label(state) if used else "unused"
		links.append({"index": index, "offset": offset, "state": state, "to_node": to_node, "used": used, "label": label})
		link_census[label] += 1
		if used:
			link_census.used += 1

	var goodies: Array[Dictionary] = []
	var goodie_census: Dictionary = {"displayable": 233, "locked": 0, "hint": 0, "new": 0, "old": 0, "unknown": 0, "reserved": 0}
	for index: int in range(300):
		var offset: int = GOODIE_OFFSET + index * 4
		var state: int = bytes.decode_u32(offset)
		var reserved: bool = index >= 233
		var label: String = "reserved" if reserved else _goodie_label(state)
		goodies.append({"index": index, "offset": offset, "state": state, "reserved": reserved, "label": label})
		goodie_census[label] += 1

	var tech_slots: Array[int] = []
	for index: int in range(32):
		tech_slots.append(bytes.decode_u32(TECH_OFFSET + index * 4))
	return {
		"ok": true, "message": "Supported career container. Unselected and unknown bytes are preserved.",
		"size": bytes.size(), "version": bytes.decode_u16(0),
		"kills": kills, "packed": packed, "nodes": nodes, "node_census": node_census,
		"completed_nodes": node_census.completed, "used_nodes": node_census.used,
		"links": links, "link_census": link_census, "goodies": goodies, "goodie_census": goodie_census,
		"tech_slots": tech_slots, "career_in_progress_raw": bytes.decode_u32(0x248A),
		"god_mode_raw": bytes.decode_u32(0x2496),
		"volumes": {"sound": _float_field(bytes, 0x248E), "music": _float_field(bytes, 0x2492)},
		"notes": [
			"The version word and length recognize this container; they do not prove its origin or gameplay validity.",
			"Packed bytes above the five kill counts are preserved. The first two store screen-position data; the other three have no known consumer.",
			"Reserved Goodie slots 233–299, unmapped rank values, options and all unselected bytes remain unchanged.",
			"Raw tech slots and god-mode state are inspection only. A save flag does not establish active game cheats.",
			"Stored sound/music values do not establish the settings that a running game will apply."
		]
	}


static func preview(original: PackedByteArray, selections: Dictionary) -> Dictionary:
	var validation: Dictionary = _validate(original)
	if not validation.ok:
		return validation
	if selections.is_empty() or selections.size() > CATEGORY_NAMES.size():
		return _failure("Select between one and five kill categories explicitly.")
	var categories: Array[int] = []
	for key: Variant in selections:
		if typeof(key) != TYPE_INT or key < 0 or key >= CATEGORY_NAMES.size():
			return _failure("A kill category must be an integer from 0 to 4.")
		var value: Variant = selections[key]
		if typeof(value) != TYPE_INT or value < 0 or value > MAX_KILLS:
			return _failure("Kill counts must be whole numbers from 0 to 16,777,215.")
		if (original.decode_u32(KILLS_OFFSET + key * 4) & MAX_KILLS) == value:
			return _failure("The selected %s count is unchanged. Remove that selection or choose a different count." % CATEGORY_NAMES[key])
		categories.append(key)
	categories.sort()
	var output: PackedByteArray = original.duplicate()
	var selected: Array[Dictionary] = []
	for category: int in categories:
		var offset: int = KILLS_OFFSET + category * 4
		var count: int = selections[category]
		# Write precisely three bytes: the packed fourth byte is never authored.
		for byte_index: int in range(3):
			output[offset + byte_index] = (count >> (byte_index * 8)) & 0xFF
		selected.append({
			"category": category, "name": CATEGORY_NAMES[category], "offset": offset,
			"before": original.decode_u32(offset) & MAX_KILLS, "after": count
		})
	var difference: Dictionary = compare(original, output)
	return {
		"ok": true, "message": "Preview only. No file has been written.", "bytes": output,
		"changes": difference.changes, "changed_bytes": difference.changed_bytes, "selected": selected,
		"summary": "%d selected categories; %d changed bytes; all other bytes preserved." % [selected.size(), difference.changed_bytes]
	}


static func compare(left: PackedByteArray, right: PackedByteArray) -> Dictionary:
	var changes: Array[Dictionary] = []
	var ranges: Array[Dictionary] = []
	var range_start: int = -1
	var differing_regions: Dictionary = {}
	var maximum: int = maxi(left.size(), right.size())
	for offset: int in range(maximum):
		var before: int = left[offset] if offset < left.size() else -1
		var after: int = right[offset] if offset < right.size() else -1
		if before != after:
			changes.append({"offset": offset, "before": before, "after": after})
			var region: String = _region(offset)
			differing_regions[region] = int(differing_regions.get(region, 0)) + 1
			if range_start == -1:
				range_start = offset
		elif range_start != -1:
			ranges.append({"start": range_start, "end": offset - 1, "length": offset - range_start})
			range_start = -1
	if range_start != -1:
		ranges.append({"start": range_start, "end": maximum - 1, "length": maximum - range_start})
	var equal: bool = changes.is_empty()
	var same_length: bool = left.size() == right.size()
	var summary: String = "Byte-for-byte identical (%d bytes)." % left.size() if equal else "%d changed bytes across %d ranges; length %d → %d bytes." % [changes.size(), ranges.size(), left.size(), right.size()]
	return {
		"ok": true, "equal": equal, "same_length": same_length,
		"left_size": left.size(), "right_size": right.size(), "changed_bytes": changes.size(),
		"changes": changes, "ranges": ranges, "regions": differing_regions, "summary": summary,
		"missing_byte": -1
	}


static func _validate(bytes: PackedByteArray) -> Dictionary:
	if bytes.size() != SIZE:
		return {"ok": false, "size": bytes.size(), "message": "Unsupported length: %d bytes. A supported career contains exactly 10,004 bytes." % bytes.size()}
	var version: int = bytes.decode_u16(0)
	if version != VERSION_WORD:
		return {"ok": false, "size": bytes.size(), "version": version, "message": "Unsupported version word 0x%04X; expected 0x4BD1." % version}
	return {"ok": true, "size": bytes.size(), "version": version}


static func _failure(message: String) -> Dictionary:
	return {"ok": false, "message": message}


static func _link_label(state: int) -> String:
	match state:
		0: return "locked"
		1: return "complete"
		2: return "broken"
		_: return "unknown"


static func _goodie_label(state: int) -> String:
	match state:
		0: return "locked"
		1: return "hint"
		2: return "new"
		3: return "old"
		_: return "unknown"


static func _float_field(bytes: PackedByteArray, offset: int) -> Dictionary:
	var value: float = bytes.decode_float(offset)
	return {"offset": offset, "raw_bits": bytes.decode_u32(offset), "value": value, "finite": is_finite(value)}


static func _region(offset: int) -> String:
	if offset < 0x0002:
		return "Version word"
	if offset < NODE_OFFSET:
		return "Career header"
	if offset < LINK_OFFSET:
		return "Mission records"
	if offset < GOODIE_OFFSET:
		return "Campaign links"
	if offset < KILLS_OFFSET:
		return "Goodie states" if offset < GOODIE_OFFSET + 233 * 4 else "Reserved Goodie slots"
	if offset < TECH_OFFSET:
		return "Packed kill bytes" if (offset - KILLS_OFFSET) % 4 == 3 else "Kill counts"
	if offset < 0x248A:
		return "Raw tech slots"
	if offset < 0x24BE:
		return "Career settings"
	if offset < SIZE:
		return "Stored options"
	return "Outside supported length"
