#!/usr/bin/env python3
"""Build a public-safe matrix summary for shipped Goodies resource archives.

Input is the packed asset manifest generated by ``tools/aya_archive_inventory.py``.
The output strips absolute paths and raw asset filenames, keeping only Goodie
indices, source-grid groups, family counts, reference counts, and unresolved-ref
counts. It does not read or write BEA.exe and does not extract private assets.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = (
    ROOT
    / "subagents"
    / "asset-coverage-2026-05-07"
    / "packed-asset-manifest.json"
)
DEFAULT_OUT = (
    ROOT
    / "subagents"
    / "goodies-asset-matrix"
    / "current"
    / "goodies-asset-matrix.json"
)

ARCHIVE_RE = re.compile(r"goodie_(\d+)_res_PC\.aya", re.IGNORECASE)
DISPLAYABLE_GOODIE_INDICES = set(range(0, 233))
SOURCE_GRID_INDICES = (
    set(range(0, 8))
    | set(range(8, 66))
    | set(range(66, 71))
    | set(range(74, 78))
    | set(range(78, 201))
    | set(range(201, 233))
)


@dataclass(frozen=True)
class GroupRange:
    key: str
    label: str
    first: int
    last: int
    source_grid_visible: bool

    def contains(self, index: int) -> bool:
        return self.first <= index <= self.last


GROUPS = (
    GroupRange("character_bios", "Character bios", 0, 7, True),
    GroupRange("unit_gallery", "Unit/gallery resources", 8, 65, True),
    GroupRange("race_levels", "Race level unlocks", 66, 70, True),
    GroupRange("ungrouped_71_73", "Goodie resources 71-73", 71, 73, False),
    GroupRange("developer_items", "Developer items", 74, 77, True),
    GroupRange("concept_art", "Concept art", 78, 200, True),
    GroupRange("fmv_cutscenes", "FMV cutscenes", 201, 232, True),
)


def relative(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def group_for(index: int) -> GroupRange | None:
    for group in GROUPS:
        if group.contains(index):
            return group
    return None


def archive_index(value: object) -> int | None:
    match = ARCHIVE_RE.search(str(value))
    if not match:
        return None
    return int(match.group(1))


def summarize_group(group: GroupRange, rows: list[dict[str, object]]) -> dict[str, object]:
    family_counts = Counter(str(row.get("family", "unknown")) for row in rows)
    texture_refs = sum(len(row.get("texture_refs", []) or []) for row in rows)
    mesh_refs = sum(len(row.get("mesh_refs", []) or []) for row in rows)
    unresolved_texture_refs = sum(
        len(row.get("texture_refs", []) or [])
        - int((row.get("resolution") or {}).get("texture_refs_resolved", 0))
        for row in rows
    )
    unresolved_mesh_refs = sum(
        len(row.get("mesh_refs", []) or [])
        - int((row.get("resolution") or {}).get("mesh_refs_resolved", 0))
        for row in rows
    )
    present = sorted(int(row["goodieIndex"]) for row in rows)
    expected = set(range(group.first, group.last + 1))
    missing = sorted(expected.difference(present))
    return {
        "key": group.key,
        "label": group.label,
        "range": [group.first, group.last],
        "sourceGridVisible": group.source_grid_visible,
        "archiveCount": len(rows),
        "missingArchiveIndices": missing,
        "families": dict(sorted(family_counts.items())),
        "referencedTextureRows": texture_refs,
        "referencedMeshRows": mesh_refs,
        "unresolvedTextureRows": unresolved_texture_refs,
        "unresolvedMeshRows": unresolved_mesh_refs,
    }


def build_matrix(manifest_path: Path) -> dict[str, object]:
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    raw_rows = manifest.get("gdie_families", [])
    rows: list[dict[str, object]] = []

    for raw in raw_rows:
        index = archive_index(raw.get("archive"))
        if index is None:
            continue
        rows.append(
            {
                "goodieIndex": index,
                "family": raw.get("family", "unknown"),
                "texture_refs": raw.get("texture_refs", []),
                "mesh_refs": raw.get("mesh_refs", []),
                "resolution": raw.get("resolution", {}),
            }
        )

    rows.sort(key=lambda row: int(row["goodieIndex"]))
    archive_indices = {int(row["goodieIndex"]) for row in rows}
    displayable_without_archive = sorted(DISPLAYABLE_GOODIE_INDICES.difference(archive_indices))
    archived_not_source_grid_visible = sorted(archive_indices.difference(SOURCE_GRID_INDICES))

    matrix_groups = []
    for group in GROUPS:
        group_rows = [row for row in rows if group.contains(int(row["goodieIndex"]))]
        matrix_groups.append(summarize_group(group, group_rows))

    manifest_summary = manifest.get("summary", {})
    unresolved_unique_refs = {
        "gdieTextureRefs": int(manifest_summary.get("gdie_texture_refs", 0))
        - int(manifest_summary.get("gdie_texture_refs_resolved", 0)),
        "gdieMeshRefs": int(manifest_summary.get("gdie_mesh_refs", 0))
        - int(manifest_summary.get("gdie_mesh_refs_resolved", 0)),
    }
    status = "PASS"
    if unresolved_unique_refs["gdieTextureRefs"] or unresolved_unique_refs["gdieMeshRefs"]:
        status = "WARN"
    if len(rows) != 232:
        status = "FAIL"

    return {
        "schema": "goodies-asset-matrix.v1",
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "sourceManifest": relative(manifest_path),
        "status": status,
        "summary": {
            "goodieArchiveRows": len(rows),
            "displayableGoodieSlots": len(DISPLAYABLE_GOODIE_INDICES),
            "displayableSlotsWithoutResourceArchive": displayable_without_archive,
            "archivedRowsNotMappedBySourceGrid": archived_not_source_grid_visible,
            "familyCounts": manifest_summary.get("gdie_family_counts", {}),
            "uniqueGdieTextureRefs": manifest_summary.get("gdie_texture_refs", 0),
            "uniqueGdieTextureRefsResolved": manifest_summary.get(
                "gdie_texture_refs_resolved", 0
            ),
            "uniqueGdieMeshRefs": manifest_summary.get("gdie_mesh_refs", 0),
            "uniqueGdieMeshRefsResolved": manifest_summary.get(
                "gdie_mesh_refs_resolved", 0
            ),
            "unresolvedUniqueRefs": unresolved_unique_refs,
        },
        "groups": matrix_groups,
        "safety": {
            "stripsAbsolutePaths": True,
            "stripsRawAssetNames": True,
            "extractsAssets": False,
            "launchesGame": False,
            "readsOrWritesOriginalExe": False,
        },
        "notes": [
            "Goodie 232 is displayable in the source grid as FMV slot 33 but has no goodie_232_res_PC.aya archive in the known PC install.",
            "Goodie resources 71-73 exist as shipped archives, but the current source get_goodie_number grid mapping does not expose them in the visible wall rows.",
            "Reference counts in groups count per-row references; unique resolved reference totals come from the packed asset manifest summary.",
        ],
    }


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the matrix cannot be built cleanly.",
    )
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    matrix = build_matrix(args.manifest)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(matrix, indent=2) + "\n", encoding="utf-8")
    print(f"{matrix['status']}: wrote {relative(args.out)}")
    print(
        "goodie archives: "
        f"{matrix['summary']['goodieArchiveRows']} / "
        f"{matrix['summary']['displayableGoodieSlots']} displayable slots"
    )
    print(
        "unique refs resolved: "
        f"textures {matrix['summary']['uniqueGdieTextureRefsResolved']}/"
        f"{matrix['summary']['uniqueGdieTextureRefs']}, "
        f"meshes {matrix['summary']['uniqueGdieMeshRefsResolved']}/"
        f"{matrix['summary']['uniqueGdieMeshRefs']}"
    )
    if args.check and matrix["status"] == "FAIL":
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
