/* address: 0x005a9d78 */
/* name: CFastVB__DispatchOp_MultiplyMatrix4x4_Packed_005a9d78 */
/* signature: int __stdcall CFastVB__DispatchOp_MultiplyMatrix4x4_Packed_005a9d78(void * param_1, void * param_2, void * param_3) */


int CFastVB__DispatchOp_MultiplyMatrix4x4_Packed_005a9d78(void *param_1,void *param_2,void *param_3)

{
  undefined4 uVar1;
  undefined4 uVar2;
  undefined4 uVar3;
  undefined8 uVar4;
  undefined8 uVar5;
  undefined8 uVar6;
  undefined8 uVar7;
  undefined8 uVar8;
  undefined8 uVar9;

  uVar1 = (undefined4)((ulonglong)*(undefined8 *)param_2 >> 0x20);
  uVar2 = (undefined4)((ulonglong)*(undefined8 *)((int)param_2 + 8) >> 0x20);
  uVar3 = (undefined4)*(undefined8 *)param_2;
  uVar6 = CONCAT44(uVar3,uVar3);
  uVar3 = (undefined4)*(undefined8 *)((int)param_2 + 8);
  uVar9 = CONCAT44(uVar3,uVar3);
  uVar7 = PackedFloatingMUL(*(undefined8 *)param_3,uVar6);
  uVar5 = CONCAT44(uVar1,uVar1);
  uVar4 = PackedFloatingMUL(uVar6,*(undefined8 *)((int)param_3 + 8));
  uVar8 = PackedFloatingMUL(*(undefined8 *)((int)param_3 + 0x10),uVar5);
  uVar6 = CONCAT44(uVar2,uVar2);
  uVar5 = PackedFloatingMUL(uVar5,*(undefined8 *)((int)param_3 + 0x18));
  uVar7 = PackedFloatingADD(uVar8,uVar7);
  uVar8 = PackedFloatingMUL(*(undefined8 *)((int)param_3 + 0x20),uVar9);
  uVar4 = PackedFloatingADD(uVar5,uVar4);
  uVar5 = PackedFloatingMUL(uVar9,*(undefined8 *)((int)param_3 + 0x28));
  uVar9 = PackedFloatingADD(uVar8,uVar7);
  uVar7 = PackedFloatingMUL(*(undefined8 *)((int)param_3 + 0x30),uVar6);
  uVar4 = PackedFloatingADD(uVar4,uVar5);
  uVar6 = PackedFloatingMUL(uVar6,*(undefined8 *)((int)param_3 + 0x38));
  uVar7 = PackedFloatingADD(uVar7,uVar9);
  uVar5 = *(undefined8 *)((int)param_2 + 0x10);
  uVar9 = PackedFloatingADD(uVar6,uVar4);
  uVar6 = *(undefined8 *)((int)param_2 + 0x18);
  *(undefined8 *)param_1 = uVar7;
  uVar4 = *(undefined8 *)param_3;
  *(undefined8 *)((int)param_1 + 8) = uVar9;
  uVar1 = (undefined4)((ulonglong)uVar5 >> 0x20);
  uVar2 = (undefined4)((ulonglong)uVar6 >> 0x20);
  uVar3 = (undefined4)uVar5;
  uVar9 = CONCAT44(uVar3,uVar3);
  uVar3 = (undefined4)uVar6;
  uVar7 = CONCAT44(uVar3,uVar3);
  uVar8 = PackedFloatingMUL(uVar4,uVar9);
  uVar5 = CONCAT44(uVar1,uVar1);
  uVar4 = PackedFloatingMUL(uVar9,*(undefined8 *)((int)param_3 + 8));
  uVar9 = PackedFloatingMUL(*(undefined8 *)((int)param_3 + 0x10),uVar5);
  uVar6 = CONCAT44(uVar2,uVar2);
  uVar5 = PackedFloatingMUL(uVar5,*(undefined8 *)((int)param_3 + 0x18));
  uVar9 = PackedFloatingADD(uVar9,uVar8);
  uVar8 = PackedFloatingMUL(*(undefined8 *)((int)param_3 + 0x20),uVar7);
  uVar4 = PackedFloatingADD(uVar5,uVar4);
  uVar5 = PackedFloatingMUL(uVar7,*(undefined8 *)((int)param_3 + 0x28));
  uVar9 = PackedFloatingADD(uVar8,uVar9);
  uVar7 = PackedFloatingMUL(*(undefined8 *)((int)param_3 + 0x30),uVar6);
  uVar4 = PackedFloatingADD(uVar4,uVar5);
  uVar6 = PackedFloatingMUL(uVar6,*(undefined8 *)((int)param_3 + 0x38));
  uVar7 = PackedFloatingADD(uVar7,uVar9);
  uVar5 = *(undefined8 *)((int)param_2 + 0x20);
  uVar9 = PackedFloatingADD(uVar6,uVar4);
  uVar6 = *(undefined8 *)((int)param_2 + 0x28);
  *(undefined8 *)((int)param_1 + 0x10) = uVar7;
  uVar4 = *(undefined8 *)param_3;
  *(undefined8 *)((int)param_1 + 0x18) = uVar9;
  uVar1 = (undefined4)((ulonglong)uVar5 >> 0x20);
  uVar2 = (undefined4)((ulonglong)uVar6 >> 0x20);
  uVar3 = (undefined4)uVar5;
  uVar9 = CONCAT44(uVar3,uVar3);
  uVar3 = (undefined4)uVar6;
  uVar7 = CONCAT44(uVar3,uVar3);
  uVar8 = PackedFloatingMUL(uVar4,uVar9);
  uVar5 = CONCAT44(uVar1,uVar1);
  uVar4 = PackedFloatingMUL(uVar9,*(undefined8 *)((int)param_3 + 8));
  uVar9 = PackedFloatingMUL(*(undefined8 *)((int)param_3 + 0x10),uVar5);
  uVar6 = CONCAT44(uVar2,uVar2);
  uVar5 = PackedFloatingMUL(uVar5,*(undefined8 *)((int)param_3 + 0x18));
  uVar9 = PackedFloatingADD(uVar9,uVar8);
  uVar8 = PackedFloatingMUL(*(undefined8 *)((int)param_3 + 0x20),uVar7);
  uVar4 = PackedFloatingADD(uVar5,uVar4);
  uVar5 = PackedFloatingMUL(uVar7,*(undefined8 *)((int)param_3 + 0x28));
  uVar9 = PackedFloatingADD(uVar8,uVar9);
  uVar7 = PackedFloatingMUL(*(undefined8 *)((int)param_3 + 0x30),uVar6);
  uVar4 = PackedFloatingADD(uVar4,uVar5);
  uVar6 = PackedFloatingMUL(uVar6,*(undefined8 *)((int)param_3 + 0x38));
  uVar7 = PackedFloatingADD(uVar7,uVar9);
  uVar5 = *(undefined8 *)((int)param_2 + 0x30);
  uVar9 = PackedFloatingADD(uVar6,uVar4);
  uVar6 = *(undefined8 *)((int)param_2 + 0x38);
  *(undefined8 *)((int)param_1 + 0x20) = uVar7;
  uVar4 = *(undefined8 *)param_3;
  *(undefined8 *)((int)param_1 + 0x28) = uVar9;
  uVar1 = (undefined4)((ulonglong)uVar5 >> 0x20);
  uVar2 = (undefined4)((ulonglong)uVar6 >> 0x20);
  uVar3 = (undefined4)uVar5;
  uVar9 = CONCAT44(uVar3,uVar3);
  uVar3 = (undefined4)uVar6;
  uVar7 = CONCAT44(uVar3,uVar3);
  uVar8 = PackedFloatingMUL(uVar4,uVar9);
  uVar5 = CONCAT44(uVar1,uVar1);
  uVar4 = PackedFloatingMUL(uVar9,*(undefined8 *)((int)param_3 + 8));
  uVar9 = PackedFloatingMUL(*(undefined8 *)((int)param_3 + 0x10),uVar5);
  uVar6 = CONCAT44(uVar2,uVar2);
  uVar5 = PackedFloatingMUL(uVar5,*(undefined8 *)((int)param_3 + 0x18));
  uVar9 = PackedFloatingADD(uVar9,uVar8);
  uVar8 = PackedFloatingMUL(*(undefined8 *)((int)param_3 + 0x20),uVar7);
  uVar4 = PackedFloatingADD(uVar5,uVar4);
  uVar5 = PackedFloatingMUL(uVar7,*(undefined8 *)((int)param_3 + 0x28));
  uVar9 = PackedFloatingADD(uVar8,uVar9);
  uVar7 = PackedFloatingMUL(*(undefined8 *)((int)param_3 + 0x30),uVar6);
  uVar5 = PackedFloatingADD(uVar4,uVar5);
  uVar6 = PackedFloatingMUL(uVar6,*(undefined8 *)((int)param_3 + 0x38));
  uVar4 = PackedFloatingADD(uVar7,uVar9);
  uVar5 = PackedFloatingADD(uVar6,uVar5);
  *(undefined8 *)((int)param_1 + 0x30) = uVar4;
  *(undefined8 *)((int)param_1 + 0x38) = uVar5;
  FastExitMediaState();
  return (int)param_1;
}
